BookstoreA/Models/Book.cs
using BookstoreA.Models;
using System.ComponentModel.DataAnnotations;

namespace BookstoreA.Models
{
    public class Book
    {
        public int Id { get; set; }

        [Display(Name = "Título")]
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        public string Title { get; set; }

        [Display(Name = "Valor")]
        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "{0:C2}")]
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        public double Price { get; set; }

        [Display(Name = "Autor")]
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        public string Author { get; set; }

        [Display(Name = "Ano de lançamento")]
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        public int ReleaseYear { get; set; }

        [Display(Name = "Gêneros Literários")]
        public ICollection<Genre> Genres { get; set; } = new List<Genre>();

        public Book()
        {

        }

        public Book(int id, string title, double price, string author, int releaseYear)
        {
            Id = id;
            Title = title;
            Price = price;
            Author = author;
            ReleaseYear = releaseYear;
        }
    }
}

BookstoreA/Models/Genre.cs
using BookstoreA.Models;
using System.ComponentModel.DataAnnotations;

namespace BookstoreA.Models
{
    public class Genre
    {
        public int Id { get; set; }

        [Display(Name = "Nome")]
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        public string Name { get; set; }

        public ICollection<Book> Books { get; set; } = new List<Book>();

        public Genre()
        {

        }

        public Genre(int id, string name)
        {
            Id = id;
            Name = name;
        }



    }
}

BookstoreA/Models/ViewModels/BookFormViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace BookstoreA.Models.ViewModels;

public class BookFormViewModel
{
    // No Create, esse é o livro que será criado
    // No Edit, é o livro que está sendo editado
    public Book Book { get; set; }

    // Essa é a lista de gêneros disponíveis, buscados no banco de dados
    public ICollection<Genre> Genres { get; set; } = new List<Genre>();

    // Essa é a lista de gêneros que foram selecionados
    // Usaremos essa propriedade para verificar se foi selecionado algum gênero
    // E também para armazenar quais gêneros o usuário selecionou
    [Display(Name = "Gêneros Literários")]
    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    public List<int> SelectedGenresIds { get; set; } = new List<int>();

    // Embora tenha uma estrutura diferente, isso é uma propriedade também, mas apenas de leitura
    // Isso porque nós já definimos o valor dela de cara
    // O valor dela é o que o método ao lado da arrow function retornar
    public List<SelectListItem> GenresSelect => GenerateGenresSelect();

    // Para exibir um item naquelas listas de seleção, ele precisa ser um objeto do tipo SelectListItem
    // Aqui pegamos a lista de gêneros, percorremos ela e criamos um objeto desse tipo para cada um
    // Cada um deles tem dois atributos, o Value e o Text
    // O Text é o que aparece na tela, queremos que apareça o nome do gênero correspondente
    // O Value é o que é salvo numa lista quando o usuário seleciona uma opção
    // Queremos que sejam salvos os ids dos gêneros que forem selecionados
    private List<SelectListItem> GenerateGenresSelect()
    {
        List<SelectListItem> genresSelect = new List<SelectListItem>();
        if (Genres is not null)
        {
            foreach (Genre genre in Genres)
            {
                genresSelect.Add(new SelectListItem { Value = genre.Id.ToString(), Text = genre.Name });
            }
        }
        return genresSelect;
    }
}

BookstoreA/Models/ViewModels/ErrorViewModel.cs
namespace BookstoreA.Models.ViewModels
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public string? Message { get; set; }
    }
}

BookstoreA/Controllers/GenresController.cs
using BookstoreA.Models;
using BookstoreA.Models.ViewModels;
using BookstoreA.Service.Exceptions;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using BookstoreA.Service;


namespace BookstoreA.Controllers;


public class GenresController : Controller
{
    private readonly GenreService _service;

    public GenresController(GenreService service)
    {
        _service = service;
    }

    public async Task<IActionResult> Index()
    {
        return View(await _service.FindAllAsync());
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Genre genre)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }

        await _service.InsertAsync(genre);

        return RedirectToAction(nameof(Index));
    }


    public async Task<IActionResult> Delete(int? id)
    {
        if (id is null)
        {
            return RedirectToAction(nameof(Error),
                new { message = "O id não foi fornecido." });
        }
        Genre genre = await _service.FindByIdAsync(id.Value);
        if (genre is null)
        {
            return RedirectToAction(nameof(Error),
                new { message = "O id não foi encontrado." });
        }

        return View(genre);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        try
        {
            await _service.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }
        catch (IntegrityException ex)
        {
            return RedirectToAction(nameof(Error), new { message = ex.Message });
        }
    }

    public async Task<IActionResult> Edit(int? id)
    {
        if (id is null)
        {
            return RedirectToAction(nameof(Error), new { message = "Id não fornecido" });
        }
        var obj = await _service.FindByIdAsync(id.Value);
        if (obj is null)
        {
            return RedirectToAction(nameof(Error), new { message = "Id não encontrado" });
        }


        return View(obj);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, Genre genre)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }

        if (id != genre.Id)
        {
            return RedirectToAction(nameof(Error), new { message = "Id's não condizentes" });
        }

        try
        {
            await _service.UpdateAsync(genre);
            return RedirectToAction(nameof(Index));
        }
        catch (ApplicationException ex)
        {
            return RedirectToAction(nameof(Error), new { message = ex.Message });
        }
    }

    public async Task<IActionResult> Details(int? id)
    {
        if (id is null)
        {
            return RedirectToAction(nameof(Error), new { message = "Id não fornecido" });
        }
        var obj = await _service.FindByIdEagerAsync(id.Value);
        if (obj is null)
        {
            return RedirectToAction(nameof(Error), new { message = "Id não encontrado" });
        }

        return View(obj);
    }

    public IActionResult Error(string message)
    {
        ErrorViewModel viewModel = new ErrorViewModel
        {
            Message = message,
            RequestId = Activity.Current?.Id
                ?? HttpContext.TraceIdentifier
        };
        return View(viewModel);
    }



}

BookstoreA/Controllers/HomeController.cs
using BookstoreA.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Bookstore.Controllers
{
    public class HomeController : Controller
    {
		private readonly ILogger<HomeController> _logger;
		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}
		public IActionResult Index()
		{
			return View();
		}
		public IActionResult Privacy()
		{
			return View();
		}
		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

BookstoreA/Views/Books/Create.cshtml
@model BookstoreA.Models.ViewModels.BookFormViewModel

@{
    ViewData["Title"] = "Criar novo livro";
}

<h1>Criar novo livro</h1>

<h4>Livro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Book.Title" class="control-label"></label>
                <input asp-for="Book.Title" class="form-control" />
                <span asp-validation-for="Book.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.Price" class="control-label"></label>
                <input asp-for="Book.Price" class="form-control" />
                <span asp-validation-for="Book.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.Author" class="control-label"></label>
                <input asp-for="Book.Author" class="form-control" />
                <span asp-validation-for="Book.Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.ReleaseYear" class="control-label"></label>
                <input asp-for="Book.ReleaseYear" class="form-control" />
                <span asp-validation-for="Book.ReleaseYear" class="text-danger"></span>
            </div>
            <div>
                @foreach (var genre in Model.GenresSelect)
                {
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="SelectedGenresIds" value="@genre.Value"
                               id="genre-@genre.Value" @(Model.SelectedGenresIds.Contains(int.Parse(genre.Value)) ? "checked" : "") />
                        <label class="form-check-label" for="genre-@genre.Value">@genre.Text</label>
                    </div>
                }
            </div><br />
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para lista de livros</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BookstoreA/Views/Books/Delete.cshtml
@model BookstoreA.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Apagar Livro</h1>

<h3>Você tem certeza que deseja apagar este livro?</h3>
<div>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseYear)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ReleaseYear)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Apagar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar para lista de livros</a>
    </form>
</div>

BookstoreA/Views/Books/Details.cshtml
@model BookstoreA.Models.Book

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <h4>Livro</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseYear)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ReleaseYear)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Genres)
        </dt>
        <dd class="col-sm-10">
            @foreach (var item in Model.Genres)
            {
                <a asp-controller="Genres" asp-action="Details" as-route-id="@item.Id">@item.Name</a>
                <br />
            }
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model?.Id">Editar</a>
    <a asp-action="Index">Voltar para lista</a>
</div>

BookstoreA/Views/Books/Edit.cshtml
@model BookstoreA.Models.ViewModels.BookFormViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Livro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Book.Id" />
            <div class="form-group">
                <label asp-for="Book.Title" class="control-label"></label>
                <input asp-for="Book.Title" class="form-control" />
                <span asp-validation-for="Book.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.Price" class="control-label"></label>
                <input asp-for="Book.Price" class="form-control" />
                <span asp-validation-for="Book.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.Author" class="control-label"></label>
                <input asp-for="Book.Author" class="form-control" />
                <span asp-validation-for="Book.Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.ReleaseYear" class="control-label"></label>
                <input asp-for="Book.ReleaseYear" class="form-control" />
                <span asp-validation-for="Book.ReleaseYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*                 @foreach (var genre in Model.Book.Genres)
                {
                <div>

                @genre.Name
                </div>
                } *@
            </div>
            <div class="form-group">
                <label asp-for="SelectedGenresIds" class="control-label"></label>
                <span class="text-muted">Selecione os Gêneros Literários</span>
                <div>
                    @foreach (var genre in Model.GenresSelect)
                    {
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" name="SelectedGenresIds" value="@genre.Value"
                                   id="genre-@genre.Value" @(Model.SelectedGenresIds.Contains(int.Parse(genre.Value)) ? "checked" : "") />
                            <label class="form-check-label" for="genre-@genre.Value">@genre.Text</label>
                        </div>
                    }
                </div>
                <span asp-validation-for="SelectedGenresIds" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a style="text-decoration: none;" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BookstoreA/Views/Books/Index.cshtml
@model IEnumerable<BookstoreA.Models.Book>

@{
    ViewData["Title"] = "Index";
}

<h1>Livros</h1>

<p>
    <a asp-action="Create" style="text-decoration: none;">Adicionar novo livro</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReleaseYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genres)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details"
                       asp-route-id="@item.Id">
                        @Html.DisplayFor(modelItem => item.Title)
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReleaseYear)
                </td>
                <td>
                    @foreach (Genre genre in item.Genres)
                    {
                        <a asp-controller="Genres"
                           asp-action="Details"
                           asp-route-id="@genre.Id"
                           style="text-decoration: none;"
                           class="text-primary">
                            @genre.Name
                        </a>
                        <br />
                    }
                </td>
                <td>
                    <a asp-action="Details"
                       asp-route-id="@item.Id"
                       title="Detalhes"
                       class="btn btn-outline-info px-2 rounded mx-1">
                        <i class="bi bi-list-ul"></i>
                    </a>
                    <a asp-action="Edit"
                       asp-route-id="@item.Id"
                       title="Editar"
                       class="btn btn-outline-warning px-2 rounded mx-1">
                        <i class="bi bi-pencil-fill"></i>
                    </a>

                    <a asp-action="Delete"
                       asp-route-id="@item.Id"
                       title="Excluir"
                       class="btn btn-outline-danger px-2 rounded mx-1">
                        <i class="bi bi-trash-fill"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

BookstoreA/Views/Genres/Create.cshtml
@model BookstoreA.Models.Genre

@{
    ViewData["Title"] = "Novo Genero Literário";
}

<h1>@ViewData["Title"]</h1>

<h4>Genre</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BookstoreA/Views/Genres/Delete.cshtml
@model BookstoreA.Models.Genre

@{
	ViewData["Title"] = "Apagar Gênero Literário";
}
<h1>@ViewData["Title"]</h1>
<h4 class="lead">Tem certeza que deseja apagar este Gênero Literário?</h4>
<div>
	<h4>Gênero Literário</h4>
	<hr />
	<dl class="row">

		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Name)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Name)
		</dd>
	</dl>

	<form asp-action="Delete">
		<input type="hidden" asp-for="Id" />
		<input type="submit" value="Apagar" class="btn btn-danger" /> |
		<a asp-action="Index">Voltar para a lista</a>
	</form>
</div>

BookstoreA/Views/Genres/Details.cshtml
@model BookstoreA.Models.Genre
@{
    ViewData["Title"] = Model.Name;
}

<h1>@ViewData["Title"]</h1>

<div>
    <h4 class="lead text-secondary">Detalhes do Gênero Literário</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2 h5">
            @Html.DisplayNameFor(Model => Model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(Model => Model.Name)
        </dd>
    </dl>
    <hr />
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title h5">Livros</h3>
        </div>
        <div class="panel-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Books.FirstOrDefault().Title)</th>
                        <th>@Html.DisplayNameFor(model => model.Books.FirstOrDefault().Price)</th>
                        <th>@Html.DisplayNameFor(model => model.Books.FirstOrDefault().Author)</th>
                        <th>@Html.DisplayNameFor(model => model.Books.FirstOrDefault().ReleaseYear)</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Book item in Model.Books)
                    {
                        <tr>
                            <td>
                                <a asp-controller="Books" asp-action="Details" asp-route-id="@item.Id">
                                    @Html.DisplayFor(modelItem => item.Title)
                                </a>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Price)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Author)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ReleaseYear)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div>
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.Id">Editar</a>
    <a asp-action="Index">Voltar para a lista</a>
</div>

BookstoreA/Views/Genres/Edit.cshtml
@model BookstoreA.Models.Genre

@{
	ViewData["Title"] = "Editar Gênero Literário";
}

<h1>@ViewData["Title"]</h1>

<h4 class="lead">Altere as informações desejadas abaixo</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<input type="hidden" asp-for="Id" />
			<div class="form-group">
				<label asp-for="Name" class="control-label"></label>
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
				<br />
			</div>
			<div class="form-group">
				<input type="submit" value="Salvar Alterações" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>
<div>
	<a asp-action="Index">Voltar Para a lista</a>
</div>
@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

BookstoreA/Views/Genres/Index.cshtml
@using BookstoreA.Models
@model IEnumerable<Genre>


@{
    ViewData["Title"] = "Gêneros Literarios";
}

<h1>@ViewData["Title"]</h1>

<p>
    <a asp-action="Create" style="text-decoration: none;">
        Adicionar novo Gênero Literário
    </a>
</p>

<table class="table table-hover">
    <tread>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th></th>
        </tr>

    </tread>
    <tbody>
        @foreach (Genre genre in Model)
        {
            <tr>
                <td>
                    <a asp-controller="Genres"
                       asp-action="Details"
                       asp-route-id="@genre.Id">
                        @Html.DisplayFor(modelGenre => genre.Name)
                    </a>
                </td>
                <td>

                    <a type="button"
                       title="Detalhes"
                       class="btn btn-outline-info px-2 rounded mx-1"
                       asp-action="Details"
                       asp-route-id="@genre.Id">
                        <i class="bi bi-list-ul"></i>
                    </a>
                    <a type="button"
                       title="Editar"
                       class="btn btn-outline-warning px-2 rounded mx-1"
                       asp-action="Edit"
                       asp-route-id="@genre.Id">
                        <i class="bi bi-pencil-fill"></i>
                    </a>
                    <a type="button"
                       title="Excluir"
                       class="btn btn-outline-danger px-2 rounded mx-1"
                       asp-action="Delete"
                       asp-route-id="@genre.Id">
                        <i class="bi bi-trash-fill"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

BookstoreA/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BookstoreA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookstoreA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookstoreA.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/bootstrap-icons/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/bootstrap-icons/font/bootstrap-icons.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookstoreA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BookstoreA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>